---
title: "Intro_Visual"
author: "Connor Mignone"
date: "4/18/2022"
output: pdf_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(readxl)
library(readr)
```

```{r}
ZestAccuracy <- read_excel("../data/ZestAccuracy.xlsx", 
    col_types = c("text", "text", "text", 
        "text", "text", "text", "text"))
View(ZestAccuracy)
```

```{r}
df<- ZestAccuracy %>% select(`Median Error`,`Within 5% of Sale Price`,`Within 10% of Sale Price`,`Within 20% of Sale Price`)
df <- data.frame(sapply(df, function(x) as.numeric(gsub("%", "", x))))

df <- cbind(df, ZestAccuracy)
```

```{r}
df1=df %>% filter(Type == 'Off-Market')
ggplot(data = df1)+
  geom_histogram(aes(Median.Error), bins = 10)+
  labs(title='Metropolitan Zestimate Median Error')+
  xlab("Percent Error")+
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_classic()+
  scale_x_continuous(labels = scales::percent_format(scale = 1,suffix = "%")) 
```

```{r}
ggplot(data = df1)+
  geom_histogram(aes(Within.5..of.Sale.Price), bins = 10)+
  labs(title='% Within 5% Error Per Metro Area')+
  xlab("Percent")+
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_classic()+
  scale_x_continuous(labels = scales::percent_format(scale = 1,suffix = "%")) 
```

